"""init profile and strategy

Revision ID: 832a544854e6
Revises: 
Create Date: 2026-09-28 17:32:35.286753+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '832a544854e6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('profile_name', sa.String(length=120), nullable=False),
    sa.Column('target_industries', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('target_regions', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('target_countries', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('company_types', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('company_size', sa.String(length=32), nullable=False),
    sa.Column('product_lines', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('application_scenarios', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('required_signals', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('exclude_signals', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('target_roles', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('daily_quota', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('high','medium','low')", name='ck_profile_priority'),
    sa.CheckConstraint('daily_quota BETWEEN 1 AND 1000', name='ck_profile_daily_quota'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('profile_name')
    )
    op.create_index('ix_profile_countries', 'customer_profile', ['target_countries'], unique=False, postgresql_using='gin')
    op.create_index('ix_profile_enabled_updated', 'customer_profile', ['is_enabled', 'updated_at'], unique=False)
    op.create_index('ix_profile_industries', 'customer_profile', ['target_industries'], unique=False, postgresql_using='gin')
    op.create_table('search_strategy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','active','paused')", name='ck_strategy_status'),
    sa.ForeignKeyConstraint(['current_version_id'], ['search_strategy_version.id'], ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['profile_id'], ['customer_profile.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('profile_id')
    )
    op.create_index('ix_strategy_status_updated', 'search_strategy', ['status', 'updated_at'], unique=False)
    op.create_table('search_strategy_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('is_committed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('ai_generate','ai_regenerate','manual_edit')", name='ck_version_source'),
    sa.ForeignKeyConstraint(['strategy_id'], ['search_strategy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'version', name='uq_version_strategy_version')
    )
    op.create_index('ix_version_strategy', 'search_strategy_version', ['strategy_id', 'version'], unique=False)
    op.create_table('strategy_channel',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=48), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('target_countries', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('strategy_summary', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['search_strategy_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'channel', name='uq_channel_version_channel')
    )
    op.create_table('strategy_query',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('country_code', sa.String(length=8), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['strategy_channel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_query_channel', 'strategy_query', ['channel_id', 'sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_query_channel', table_name='strategy_query')
    op.drop_table('strategy_query')
    op.drop_table('strategy_channel')
    op.drop_index('ix_version_strategy', table_name='search_strategy_version')
    op.drop_table('search_strategy_version')
    op.drop_index('ix_strategy_status_updated', table_name='search_strategy')
    op.drop_table('search_strategy')
    op.drop_index('ix_profile_industries', table_name='customer_profile', postgresql_using='gin')
    op.drop_index('ix_profile_enabled_updated', table_name='customer_profile')
    op.drop_index('ix_profile_countries', table_name='customer_profile', postgresql_using='gin')
    op.drop_table('customer_profile')
    # ### end Alembic commands ###
